name: datafusion

services:
  datafusion:
    build: .
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "9000:9000"  # For metrics
    volumes:
      - ./data:/app/data
    environment:
      - RUST_LOG=info
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=transactions
      - API_PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    user: "0:0"  # Run as root to avoid permission issues
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    healthcheck:
      test: echo srvr | nc localhost 2181 || exit 1
      interval: 30s
      timeout: 3s
      retries: 3

  kafka:
    image: confluentinc/cp-kafka:latest
    user: "0:0"  # Run as root to avoid permission issues
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms512M"
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:9092 --list || exit 1
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  zookeeper_data:
  zookeeper_log:
  kafka_data:
